sudo: false

language: python

python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - DJANGO_VERSION="Django>=2.0,<2.1"
    - DJANGO_VERSION="Django>=2.1,<2.2"
    - DJANGO_VERSION="Django>=2.2,<3.0"
    - DJANGO_VERSION="Django>=3.0,<3.1"
    - DJANGO_VERSION="--pre Django>=3.1,<3.2"
    - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install 'coverage<4' # coverage>=4 has issues with python3
  - pip install -q $DJANGO_VERSION
  - pip install -q coveralls flake8
  - pip install -r demoproject/requirements.txt
  - pip install -r requirements.txt

matrix:
  allow_failures:
    - env: DJANGO_VERSION="--pre Django>=3.1,<3.2"
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

script:
    - flake8
    - django-admin --version
    - python -Wall $VIRTUAL_ENV/bin/coverage run setup.py test

after_success:
    - coveralls

addons:
  postgresql: "9.5"
